spring:
  data:
    redis:
      host: 192.168.200.130
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 跨域检测的有效期,单位s
            maxAge: 36000
      routes:
        # 认证中心
        - id: share-auth
          uri: lb://share-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - CacheRequestFilter
            - ValidateCodeFilter
            - StripPrefix=1
        # 代码生成
        - id: share-gen
          uri: lb://share-gen
          predicates:
            - Path=/code/**
          filters:
            - StripPrefix=1
        # 定时任务
        - id: share-job
          uri: lb://share-job
          predicates:
            - Path=/schedule/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: share-system
          uri: lb://share-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        # 文件服务
        - id: share-file
          uri: lb://share-file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
        - id: share-device
          uri: lb://share-device
          predicates:
            - Path=/device/**
          filters:
            - StripPrefix=1
        - id: share-user
          uri: lb://share-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: share-payment
          uri: lb://share-payment
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1
        - id: share-rule
          uri: lb://share-rule
          predicates:
            - Path=/rule/**
          filters:
            - StripPrefix=1
        - id: share-order
          uri: lb://share-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: share-ai
          uri: lb://share-ai
          predicates:
            - Path=/usersta/**
        - id: share-stastics
          uri: lb://share-stastics
          predicates:
            - Path=/sta/**
# 安全配置
security:
  # 验证码
  captcha:
    enabled: true
    type: math
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
      - /system/notice
  # 不校验白名单
  ignore:
    whites:
      - /auth/logout
      - /auth/login
      - /auth/register
      - /*/v2/api-docs
      - /csrf
      - /auth/h5/**
      - /device/emqx/**